"use client"
import './globals.css'
import {ThemeProvider} from "next-themes";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen w-screen bg-blue-950">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          </ThemeProvider>
        </main>
      </body>
    </html>
  )
}
