// "use client";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import SupabaseProvider from "@/components/providers/supabase-provider";
import SupabaseAuthProvider from "@/components/providers/supabase-auth-provider";
import { createClient } from "@/utils/supabase-server";
import "server-only";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createClient();
  // const {
  //   data: { session },
  // } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          {/*<SupabaseAuthProvider serverSession={session}>*/}
          <SupabaseAuthProvider>
            {/*<ThemeProvider attribute="class" defaultTheme="system" enableSystem>*/}
            <main className="min-h-screen max-w-screen bg-background">
              {children}
            </main>
            {/*</ThemeProvider>*/}
          </SupabaseAuthProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
